 export default class actionTypes {
    static LOG_IN = "LOG_IN"
    static LOG_OUT = "LOG_OUT"
    static LOG_IN_MESSAGES = "LOG_IN_MESSAGES"
    static CLEAR_LOG_IN_MESSAGES = "CLEAR_LOG_IN_MESSAGES"
    static GET_VACATIONS = "GET_VACATIONS"
    static POST_VACATION_MESSAGE = "POST_VACATION_MESSAGE"
    static DELETE_VACATION_MESSAGE = "DELETE_VACATION_MESSAGE"
    static DELETE_VACATION = "DELETE_VACATION"
    static GET_FOLLOWED_VACATIONS = "GET_FOLLOWED_VACATIONS"
    static RESET_VACATIONS = "RESET_VACATIONS"
    static EDIT_VACATION = "EDIT_VACATION"
    static REGISTER_USER = "REGISTER_USER"
    static DELETE_REGISTER_USER_MESSAGE = "DELETE_REGISTER_USER_MESSAGE"
}

